<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'formelement' => '/FormElement.php',
                'formlexer' => '/FormLexer.php',
                'formparser' => '/FormParser.php',
                'formparsertest' => '/tests/FormPaserTest.php',
                'lexer' => '/Lexer.php',
                'multilinetext' => '/MultiLineText.php',
                'multiplechoice' => '/MultipleChoice.php',
                'parser' => '/Parser.php',
                'singlelinetext' => '/SingleLineText.php',
                'submit' => '/Submit.php',
                'token' => '/Token.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
